---
- name: email sent
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Email sending
      community.general.mail:
          host: mail.sltidc.lk
          port: 25
          username: csalerts@sltidc.lk
          password: "11,DiVERc,#"
          sender: csalerts@sltidc.lk
          to: csalerts@sltidc.lk
          subject: Ansible-report
          body: rat is been successfully provisioned
      delegate_to: localhost
...